A little escalator update.
jonafanho/Minecraft-Transit-Railway pull request #651
Opened 2023-03-22 18:45 UTC by NatureGecko

Changes made.
- New model for the escalator. 
- Stop and change direction of the escalator using a brush. ( forward > stop > backward instead of only forward and backward )
- Change escalator block render option from "solid" to "cutoff".

https://user-images.githubusercontent.com/59920578/227006038-39c315b8-f1be-4ed2-a3ad-a6e210c2ee74.mp4

2023-03-23 16:33 UTC, Ultimate-USA-YT commented
This is Impressive!

2023-03-24 16:27 UTC, EpicPuppy613 requested changes
`registerBlockRenderType` for `Blocks.ESCALATOR_STEP` and `ESCALATOR_SIDE` should be moved outside of the `!Keys.LIFTS_ONLY` section.

2023-03-24 16:27 UTC, EpicPuppy613 commented on common/src/main/java/mtr/MTRClient.java
Did you intend to put the new escalator cutout renderer under the not lifts only section?

2023-03-25 11:12 UTC, NatureGecko commented
> [EpicPuppy613](/EpicPuppy613)
 :)
Got the point and moved to their proper place, thanks for your suggestion.

2023-03-27 00:38 UTC, EpicPuppy613 approved these changes
Much better, keep up the good work!

2023-04-13 02:31 UTC, merged